services:
  app:
    build:
      context: .
      dockerfile: infrastructure/dev/Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1000}'
    container_name: microservices-billing-app
    ports:
      - '${APP_PORT:-8001}:8000'
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --watch
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - billing-net

  mongodb:
    image: mongo:8.2.1
    container_name: microservices-billing-mongodb
    ports:
      - '${FORWARD_MONGODB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_DATABASE}'
    volumes:
      - mongodb-billing-data:/data/db
    networks:
      - billing-net

  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - billing-net

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - billing-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - billing-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infrastructure/grafana/loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - billing-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./infrastructure/grafana/promtail.yaml:/etc/promtail/config.yml
      - ./storage/logs:/var/log/laravel:ro
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - billing-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - billing-net

  tempo:
    image: grafana/tempo:latest
    user: "0:0"  # Ejecutar como root para evitar problemas de permisos
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./infrastructure/grafana/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    networks:
      - billing-net

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - billing-net

volumes:
  mongodb-billing-data:
  redis-data:
  rabbitmq-data:
  grafana-data:
  loki-data:
  prometheus-data:
  tempo-data:

networks:
  billing-net:
    driver: bridge
