global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Reglas de alerta
rule_files:
# - "alerts.yml"

scrape_configs:
  # Métricas de Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas del sistema (CPU, RAM, Disco)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Métricas de Laravel
  - job_name: 'billing-service'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'

  # Métricas de Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Métricas de Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
